TRANSACTIONS_API_URL = "https://testnet.mirrornode.hedera.com/api/v1/transactions?limit={limit}&order={order}&timestamp=gte%3A{start_time}&transactiontype={transaction_type}"
CRYPTO_TRANSFER_INITIAL_STORAGE_FILE = "data/jsons/crypto_transfer.json"
CRYPTO_TRANSFER_TABLE_NAME = "crypto_transfer"
CRYPTO_TRANSFER_PREDICTION_STORAGE_FILE = "data/jsons/predictions.json"
CRYPTO_TRANSFER_PREDICTION_PLOT_FILE = "data/outputs/predictions.png"
DUCKDB_DATABASE = "data/staging/data.duckdb"
ATLAS_URI = "mongodb+srv://<username>:<password>@cluster0.nzbehil.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"